/*
description: Include all available easing animations
*/

#include "easing/back.gdshaderinc"
#include "easing/bounce.gdshaderinc"
#include "easing/circular.gdshaderinc"
#include "easing/cubic.gdshaderinc"
#include "easing/elastic.gdshaderinc"
#include "easing/exponential.gdshaderinc"
#include "easing/linear.gdshaderinc"
#include "easing/quadratic.gdshaderinc"
#include "easing/quartic.gdshaderinc"
#include "easing/quintic.gdshaderinc"
#include "easing/sine.gdshaderinc"
