#include "../../math/const.gdshaderinc"

/*
contributors: Hugh Kennedy (https://github.com/hughsk)
description: Sine easing. From https://github.com/stackgl/glsl-easings
use: sine<In|Out|InOut>(<float> x)
examples:
    - https://raw.githubusercontent.com/patriciogonzalezvivo/lygia_examples/main/animation_easing.frag
*/

#include "sineIn.gdshaderinc"
#include "sineOut.gdshaderinc"
#include "sineInOut.gdshaderinc"
